# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\chane\Desktop\Softs\Any\TerffexCraftShop\css\others\untitled4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Grades(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.update_grades_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_grades_btn.setGeometry(QtCore.QRect(10, 10, 781, 23))
        self.update_grades_btn.setObjectName("update_grades_btn")
        self.grades_table = QtWidgets.QTableWidget(self.centralwidget)
        self.grades_table.setGeometry(QtCore.QRect(10, 40, 781, 521))
        self.grades_table.setObjectName("tableWidget")
        self.grades_table.setColumnCount(0)
        self.grades_table.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.update_grades_btn.setText(_translate("MainWindow", "Обновить"))
