# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\chane\Desktop\Softs\Any\TerffexCraftShop\css\untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(346, 429)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(110, 40, 121, 16))
        self.title.setObjectName("label")
        self.open_diary_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_diary_btn.setGeometry(QtCore.QRect(80, 90, 181, 31))
        self.open_diary_btn.setObjectName("pushButton")
        self.open_schedule_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_schedule_btn.setGeometry(QtCore.QRect(80, 130, 181, 31))
        self.open_schedule_btn.setObjectName("pushButton_2")
        self.open_grades_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_grades_btn.setGeometry(QtCore.QRect(80, 170, 181, 31))
        self.open_grades_btn.setObjectName("pushButton_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 340, 185, 34))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.date_now = QtWidgets.QLabel(self.widget)
        self.date_now.setObjectName("label_2")
        self.verticalLayout.addWidget(self.date_now)
        self.time_now = QtWidgets.QLabel(self.widget)
        self.time_now.setObjectName("label_3")
        self.verticalLayout.addWidget(self.time_now)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 346, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.title.setBuddy(self.title)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.open_diary_btn, self.open_schedule_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Электронный дневник"))
        self.open_diary_btn.setText(_translate("MainWindow", "Открыть дневник"))
        self.open_schedule_btn.setText(_translate("MainWindow", "Открыть расписание"))
        self.open_grades_btn.setText(_translate("MainWindow", "Таблица оценок"))
        self.date_now.setText(_translate("MainWindow", "Сегодня Понедельник, 1 Сентября."))
        self.time_now.setText(_translate("MainWindow", "Время: 00:00:00"))

