# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\chane\Desktop\Softs\Any\TerffexCraftShop\css\untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton


class Ui_Schedule(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 363)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_lsn = QPushButton('+', self)
        self.add_lsn.setGeometry(20, 321, 20, 20)
        self.remove_lsn = QPushButton('-', self)
        self.remove_lsn.setGeometry(40, 321, 20, 20)
        self.save_btn = QPushButton('Сохранить все', self)
        self.save_btn.setGeometry(60, 321, 100, 20)
        self.upd_btn = QPushButton('Обновить', self)
        self.upd_btn.setGeometry(160, 321, 60, 20)
        self.days_of_week = QtWidgets.QComboBox(self.centralwidget)
        self.days_of_week.setGeometry(QtCore.QRect(20, 20, 451, 21))
        self.days_of_week.setObjectName("comboBox")
        self.days_of_week.addItem("")
        self.days_of_week.addItem("")
        self.days_of_week.addItem("")
        self.days_of_week.addItem("")
        self.days_of_week.addItem("")
        self.days_of_week.addItem("")
        self.lessons_table = QtWidgets.QTableWidget(self.centralwidget)
        self.lessons_table.setGeometry(QtCore.QRect(20, 60, 451, 261))
        self.lessons_table.setObjectName("tableWidget")
        self.lessons_table.setColumnCount(0)
        self.lessons_table.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.days_of_week.setItemText(0, _translate("MainWindow", "Понедельник"))
        self.days_of_week.setItemText(1, _translate("MainWindow", "Вторник"))
        self.days_of_week.setItemText(2, _translate("MainWindow", "Среда"))
        self.days_of_week.setItemText(3, _translate("MainWindow", "Четверг"))
        self.days_of_week.setItemText(4, _translate("MainWindow", "Пятница"))
        self.days_of_week.setItemText(5, _translate("MainWindow", "Суббота"))
